context:
  name: pqrs
  version: "0.3.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/manojkarthick/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 10424171488a720c0252d510f9d8e70ece270dbdf0c0c5907a5574096bca1146

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses

tests:
  - script:
      - pqrs --help

about:
  homepage: https://github.com/manojkarthick/pqrs
  summary: Command line tool for inspecting Parquet files
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  repository: https://github.com/manojkarthick/pqrs

extra:
  recipe-maintainers:
    - delsner
